NBV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('School.urls')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

School/urls.py
from django.urls import path
from . import views
from django.contrib import admin


admin.site.site_header='NBV School Portal'
admin.site.site_title='NBV Adminstration'
admin.site.index_title='Welcome to NBV Portal'
urlpatterns=[
    path('', views.index),
    path('/', views.home),
    path('aboutus', views.aboutus),
    path("contact", views.contact),
    path("events", views.events),
    path("courses", views.course),
    path("classes/<str:class_name>/", views.classes, name='class_page'),
]

School/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=10)
    desc = models.TextField(max_length=4000)

    def __str__(self):
        return self.name + ' - ' + self.email


class Subject(models.Model):
    subject_name = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='subject_logos/', null=True, blank=True)
    # classes = models.CharField(max_length=50)


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    # images = models.ImageField(upload_to='event_img/', null=True, blank=True)

    def __str__(self):
        return self.title


class EventImage(models.Model):

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    images=models.ImageField(upload_to='event_img/', null=True, blank=True)

    def __str__(self):
        return f"Image for {self.event.title}"

School/forms.py
from django import forms
from .models import Subject


class ClassSelectionForm(forms.Form):
    selected_class = forms.ModelChoiceField(queryset=Subject.objects.all())

School/views.py
from django.shortcuts import render
from School.models import Contact, Subject, Event, EventImage
from .forms import ClassSelectionForm
from django.contrib import messages


def index(request):
    return render(request, "index.html")


def home(request):
    return render(request, "index.html")


def aboutus(request):
    return render(request, "about.html")


def course(request):
    return render(request, "courses.html")


def events(request):
    events = Event.objects.all()
    context = {'events': events}
    return render(request, "events.html", context)


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        description = request.POST['description']
        # print('post worked')
        contact = Contact(name=name, email=email, phone=phone, desc=description)
        contact.save()
        messages.success(request, 'Form Submitted Successfully!')

    return render(request, "contact.html")


def classes(request, class_name):
    # selected_class = Class.objects.get(name=class_name)
    subjects = Subject.objects.filter(name=class_name)
    return render(request, 'classes.html', {'class_name': class_name, 'subjects': subjects})
    # subjects = Subject.objects.filter(classes__name=class_name)
    # return render(request, 'classes.html', {'class_name': class_name, 'subjects': subjects})

templates/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <body class="about-page">
     <div class="container2">
        {% include 'header.html' %}
        <div class="content">
            <div class="about-section">
                <div class="about-image">
                    <img src="{% static 'img/dad1.jpg' %}" alt="About Us Image">
                    <h2 class="intro"> Mr. Haranadh Chongala </h2>
                </div>
                <div class="about-details">
                    <h1>About Founder</h1>
                          <p>
                              Introducing an esteemed Headmaster, a visionary leader who stands at the forefront of educational excellence. With an unwavering commitment to fostering a positive learning environment, this exceptional headmaster brings a wealth of experience and a passion for nurturing young minds.
                          </p>

                          <p>
                              Guided by a deep understanding of educational trends and innovative teaching methods, the headmaster leads with an inclusive approach that ensures each student receives personalized support tailored to their unique strengths and needs.
                          </p>

                          <p>
                              As a mentor and role model, the headmaster cultivates a culture of respect, empathy, and collaboration among students, teachers, and parents. Their approachable nature encourages open communication and meaningful partnerships, creating a strong foundation for academic success.
                          </p>

                          <p>
                              Beyond academic achievements, the headmaster places a strong emphasis on character development, instilling values of integrity, responsibility, and social awareness. Through inspirational leadership, they motivate students to become responsible citizens and compassionate individuals poised to make positive contributions to society.
                          </p>

                          <p>
                              With a forward-thinking vision, the headmaster actively seeks opportunities to enhance the school's offerings by integrating technology, creative arts, and sports into the curriculum. Their dedication to providing a comprehensive education ensures students are well-prepared for success in both academics and life.
                          </p>

                          <p>
                              The school community is indeed fortunate to have the guidance of such a dynamic and empathetic headmaster. Under their leadership, students are poised to thrive and excel, emerging as leaders and influencers of tomorrow's world.
                          </p>
                          <div class="vertical-space"></div>
                          <b>M.A., B.Ed., CTTC </b>
                          <div class="vertical-space"></div>
                          <b>Contact no: 9553522292 </b>
                </div>

            </div>
        </div>
        <div class="content">
                <div class="about-section">
                    <div class="about-details">
                        <h1>About Principle</h1>
                            <p class="description">
                                The principal madam is the heart and soul of the institution, embodying qualities that inspire and lead to positive transformations. With a clear vision and unwavering dedication, she guides the school towards educational excellence.
                            </p>

                            <p class="description">
                                Beyond administrative tasks, the principal madam is a visionary leader who fosters a culture of collaboration and innovation. She empowers educators and staff to bring out their best, creating an environment where every student's potential is nurtured.
                            </p>

                            <p class="description">
                                One of the hallmarks of the principal madam is her ability to connect with students. She knows each student by name and takes a genuine interest in their well-being and success. Her approachable nature creates a safe space where students can freely express themselves.
                            </p>

                            <p class="description">
                                The principal madam is a problem solver, adept at handling challenges and finding creative solutions. She builds relationships with parents, engaging them as partners in their child's education journey, and ensuring a strong sense of community.
                            </p>

                            <p class="description">
                                Leading by example, the principal madam sets high standards of integrity, ethics, and professionalism. She prioritizes inclusivity, diversity, and respect, cultivating an atmosphere where everyone feels valued and accepted.
                            </p>

                            <p class="description">
                                The impact of the principal madam reaches far beyond the academic years. Her legacy echoes in the achievements of students, the dedication of teachers, and the positive spirit of the entire school community. Her influence shapes the future of generations to come.
                            </p>
                            <div class="vertical-space"></div>
                            <b>M.A., B.Ed</b>
                            <div class="vertical-space"></div>
                            <b>Contact no: 879793585</b>
                    </div>
                    <div class="about-image2">
                        <img src="{% static 'img/mom1.png' %}" alt="About Us Image">
                        <h2 class="intro"> Ms. Ramana Chongala </h2>
                    </div>
                </div>
        </div>
         <marquee direction="left" behavior="scroll" scrollamount="9">
                         <img src="{%static 'img/marquee3.jpg'%}" alt="Scrolling Image">
                         <img src="{%static 'img/marquee3.jpg'%}" alt="Scrolling Image">
                         <img src="{%static 'img/marquee3.jpg'%}" alt="Scrolling Image">
         </marquee>
     </div>
  </body>
{% include 'footer.html' %}
</html>

templates/classes.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <style>
        /* Style for the Go Back button */
        button {
          padding: 10px 20px;
          background-color: #007bff;
          color: #fff;
          border: none;
          cursor: pointer;
          margin-right: 15px;
          font-size: 16px;
          border-radius: 5px;
          transition: background-color 0.3s ease-in-out;
        }

        button:hover {
          background-color: #0056b3;
        }

            footer {
                background-color: #1b2945;
                color: white;
                text-align: center;
                position: absolute;
                bottom: auto; /* Position the footer at the bottom of the viewport */
                width: 100%;
    <!--            margin-top: 480px;-->
            }

            .subject-list {
                list-style: none;
                display: flex;
                flex-wrap: wrap;
                padding: 10px;
                margin-bottom: 320px;
                transition: transform 0.5s ease-in-out;
            }

            .subject-list :hover {
              transform: scale(1.1);
            }
            .subject-item {
                width: calc(33.33% - 20px);
                margin: 10px;
                text-align: center;
                background-color: #fff;
                border-radius: 5px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            }

            .subject-content {
                display: flex;
                flex-direction: column;
                align-items: center;
                padding: 20px;
            }

            .subject-logo img {
                max-width: 100px;
                height: auto;
            }

            .subject-name {
                font-size: 16px;
                font-weight: bold;
                color: #333;
                margin-top: 10px;
            }

            h1 {
                  margin-left: 15px;
                        font-family: 'Brush Script', cursive;
                      }

            h2 {
                        font-family: 'Brush Script', cursive;
                      }

        </style>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>NBV School</title>
    <!--    <link rel="stylesheet" href= "static/css/carousel.css">-->
        <script src="{%static 'js/carousel.js' %}" ></script>
    </head>
        <header class="header">
            <a href="/"><img src="{%static 'img/logo.png'%}" alt="Logo" class="logo"></a>
             <nav class="nav-links">
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><button id="goBackButton">Go Back</button></li>
<!--                        <li><a href="sections">Courses</a></li>-->
                    </ul>
             </nav>
        </header>
        <head>
            <div class="vertical-space"></div>
            <div class="vertical-space"></div>
            <div class="vertical-space"></div>
        <title>{{ class_name }}</title>
                <!-- In your HTML template -->
            <link rel="stylesheet" type="text/css" href="{% static 'css/carousel.css' %}">
            </head>
                <h1>{{ class_name }}</h1>

            <body class="cl-page">
              <div class="block-container">
                  <ul class="subject-list">
                        {% for subject in subjects %}
                        <li class="subject-item">
                            <div class="subject-content">
                                <div class="subject-logo">
                                    {% if subject.logo %}
                                    <img src="{{ subject.logo.url }}" alt="{{ subject.subject_name }}" class="logo-image">
                                    {% else %}
                                    No logo available
                                    {% endif %}
                                </div>
                                <h2 class="subject-name">{{ subject.subject_name }}</h2>
                            </div>
                        </li>
                        {% endfor %}
                  </ul>
                    <script>
                      const goBackButton = document.getElementById("goBackButton");
                      goBackButton.addEventListener("click", function() {
                        history.back();
                      });
                    </script>
    <!--            <ul>-->
    <!--                {% for subject in subjects %}-->
    <!--                <li>-->
    <!--&lt;!&ndash;                    {{ subject.name }}&ndash;&gt;-->
    <!--                    {% if subject.logo %}-->
    <!--                    <img src="{{ subject.logo.url }}" alt="{{ subject.subject_name }}" class="logo-image">-->
    <!--                    <h3 class="subject_name">{{ subject.subject_name }}</h3>-->
    <!--                    {% else %}-->
    <!--                    No logo available-->
    <!--                    {% endif %}-->
    <!--                </li>-->
    <!--                {% endfor %}-->
    <!--            </ul>-->
              </div>
            </body>
    {% include 'footer.html' %}

</html>

templates/contact.html
<!doctype html>
<html lang="en">
{% csrf_token %}
{% load static %}
{% include 'header.html' %}
  <head>
      {% csrf_token %}
   <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
        }

        .contact-form {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            text-align: center;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        label {
            font-weight: bold;
            margin-bottom: 6px;
            margin-right: auto;
        }
        .mg {
            font-weight: bold;
            margin-top: 5px;
            margin-bottom: 30px;
            text-align: center;
        }

        input, textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            resize: vertical;
        }

        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        button:hover {
            background-color: #0056b3;
        }


        body.dark-mode {
                background-color: #1b1b1b;
                color: #f5f5f5;
         }

         .contact-dark-mode {
            background-color: #1b2945;
            color: #f5f5f5;
            border: none;
            padding: 10px 20px;
            margin-right: 15px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out; /* Add background color transition */
         }

         .contact-dark-mode:hover {
            background-color: #000;
         }

        body.dark-mode h1 {
            color: #000;
        }

        body.dark-mode label {
            color: #000;
        }

        .success-message {
            background-color: #4CAF50;
            color: white;
            text-align: center;
            padding: 10px;
            position: fixed;
            bottom: 20px;
            left: 50%;
            transform: translateX(-50%);
            border-radius: 5px;
            z-index: 9999;
            transition: opacity 0.5s;
        }

        .hidden {
            opacity: 0;
        }




   </style>
  </head>
      <body>
<!--      <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSckzw3SEHTtC_ExKCRPL14KPR0vV_K7gcQHZA7I8rqZrSu6dw/viewform?embedded=true" width="640" height="821" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>-->
      {% csrf_token %}
       <div class="vertical-space"></div>
       <div class="vertical-space"></div>
       <div class="vertical-space"></div>
        <div class="contact-form">
            {% csrf_token %}
<!--            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSckzw3SEHTtC_ExKCRPL14KPR0vV_K7gcQHZA7I8rqZrSu6dw/viewform?embedded=true" width="640" height="821" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>-->
            <h1>Contact Us</h1>
            <form action="/contact" method="post">
               {% csrf_token %}
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required>

                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>

                <label for="phone">Phone Number:</label>
                <input type="phone" id="phone" name="phone" required>

                <label for="description">Description:</label>
                <textarea id="description" name="description" rows="4" required></textarea>

                <button type="submit">Submit</button>
            </form>

            <div class="vertical-space"></div>
<!--            <div id="success-message" class="success-message hidden">Form submitted successfully!</div>-->
        </div>
         <div class="mg">
              {% for msg in messages %}
                        <div class="alert alert-success" id="success-message">
                            {{ msg }}
                        </div>
              {% endfor %}
         </div>
      <script>
           document.addEventListener("DOMContentLoaded", function () {

                const darkModeListItem = document.getElementById("darkModeListItem");
                if (darkModeListItem) {
                    darkModeListItem.remove();
                }

                // Add a new button to the navbar on the about page
                const navbar = document.querySelector("nav ul");
                const newButton = document.createElement("button");
                newButton.textContent = "Night Mode";
                newButton.className = "contact-dark-mode";
                const liElement = document.createElement("li");
                liElement.appendChild(newButton);
                navbar.appendChild(liElement);
                const toggleButton = document.querySelector(".contact-dark-mode");
                toggleButton.addEventListener("click", function () {
                    document.body.classList.toggle("dark-mode");
                });


<!--                const successMessage = document.getElementById("success-message");-->

<!--                // Show the success message-->
<!--                successMessage.classList.remove("hidden");-->

<!--                // Hide the success message after 5 seconds-->
<!--                setTimeout(function() {-->
<!--                    successMessage.classList.add("hidden");-->
<!--                }, 3000);-->


                    const successMessage = document.getElementById("success-message");
                    if (successMessage) {
                        setTimeout(function() {
                            successMessage.style.display = "none";
                        }, 3000); // Hide after 5 seconds (adjust as needed)
                    }

           });

        </script>
    </body>
{% include 'footer.html' %}
</html>

templates/events.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
        <head>
            <style>
                h1 {
                    text-align: center;
                    padding: 20px;
                }

                .image-container {
                    display: flex;
                    flex-wrap: wrap;
                    justify-content: center;
                    margin-bottom: 40px;
                }

                .image-container .image {
                    width: 30%;
                    margin: 10px;
                    overflow: hidden;
                    transition: transform 0.3s;
                    box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.5);
                }

                .image-container .image img {
                    width: 100%;
                    height: 280px;
                    margin-right: 20px;
                    display: block;
                }

                .image-container .image:hover {
                    transform: scale(1.2);
                    box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.7);
                }


                    body .dark-mode .image-container .image {
                    width: 30%;
                    margin: 10px;
                    overflow: hidden;
                    transition: transform 0.3s, box-shadow 0.3s;
                    box-shadow: 0px 3px 10px rgba(255, 255, 255, 0.5); /* Adjust the shadow values for darkness */
                }

                body.dark-mode .image-container .image:hover {
                    transform: scale(1.2);
                    box-shadow: 0px 8px 20px rgba(255, 255, 255, 0.7); /* Adjust the shadow values for hover effect */
                }

                h1{
                   flex:1;
                   text-align: left;
                }

                 body.dark-mode .event-page{
                         background-color: #252525;
                         color: #f5f5f5;
                    }


                 body.dark-mode .toggl-dark-mode .event-page{
                                     background-color: #252525;
                                     color: #f5f5f5;
                                }

                 body.dark-mode {
                    background-color: #1b1b1b;
                    color: #f5f5f5;
                 }

                 .toggl-dark-mode {
                    background-color: #1b2945;
                    color: #f5f5f5;
                    border: none;
                    padding: 10px 20px;
                    margin-right: 15px;
                    cursor: pointer;
                    font-size: 16px;
                    transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out; /* Add background color transition */
                 }

                 .toggl-dark-mode:hover {
                    background-color: #000;
                 }

                 body.dark-mode .toggl-dark-mode {
                    background-color: #000; /* Change background color in dark mode */
                    color: #f5f5f5; /* Change color in dark mode */
                 }

                h1 {
                    font-family: 'Brush Script', cursive;
                  }
                .text-container {
                     margin-left: 20px; /* Adjust the value as needed */
                     font-family: 'Brush Script', cursive;
                  }

                </style>
        </head>
        <body class="events-page">
            {% include 'header.html' %}
            <div class="vertical-space"></div>
            <div class="vertical-space"></div>
            <div class="vertical-space"></div>
            {% for event in events %}
                <h1>{{ event.title }}</h1>
                <div class="text-container">
                    <p>{{ event.description }}</p>
                    <div class="vertical-space"></div>
                </div>
                <div class="image-container">
                    {% for image in event.eventimage_set.all %}
                        <div class="image">
                            <img src="{{ image.images.url }}" alt="{{ event.title }} Image">
                        </div>
                        {% if forloop.counter|divisibleby:3 and not forloop.last %}
                            </div><div class="image-container">
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}


<!--            <h1>Sankranti</h1>-->
<!--            <div class="image-container">-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/sankranti1.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/sankranti2.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/sankranti3.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="vertical-space"></div>-->
<!--            <h1>Independence Day</h1>-->
<!--            <div class="image-container">-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/ID1.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/ID2.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/ID3.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--            </div>-->
<!--            <h1>Mehandi Event</h1>-->
<!--            <div class="image-container">-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/M1.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/M2.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/M3.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--            </div>-->
<!--            <h1>New Year</h1>-->
<!--            <div class="image-container">-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/NY1.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/NY5.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/NY3.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--                <div class="vertical-space"></div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/NY4.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/NY2.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/NY6.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--            </div>-->
<!--            <h1>Tribute</h1>-->
<!--            <div class="image-container">-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/cert.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/both.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/bbbb.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/AW3.jpg'%}" alt="Image 1">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/AW1.jpg'%}" alt="Image 2">-->
<!--                </div>-->
<!--                <div class="image">-->
<!--                    <img src="{% static 'img/AW4.jpg'%}" alt="Image 3">-->
<!--                </div>-->
<!--            </div>-->
        <script>
           document.addEventListener("DOMContentLoaded", function () {

                const darkModeListItem = document.getElementById("darkModeListItem");
                if (darkModeListItem) {
                    darkModeListItem.remove();
                }

                // Add a new button to the navbar on the about page
                const navbar = document.querySelector("nav ul");
                const newButton = document.createElement("button");
                newButton.textContent = "Night Mode";
                newButton.className = "toggl-dark-mode";
                const liElement = document.createElement("li");
                liElement.appendChild(newButton);
                navbar.appendChild(liElement);
                const toggleButton = document.querySelector(".toggl-dark-mode");
                toggleButton.addEventListener("click", function () {
                    document.body.classList.toggle("dark-mode");
                });

           });

        </script>
        </body>
{%include 'footer.html' %}
</html>

templates/footer.html
{% load static %}
<footer>
        <p>&copy; 2023 NBV School. All rights reserved.</p>
</footer>